# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import eda_schema_pb2 as eda__schema__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in eda_schema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdaSchemaServiceStub(object):
    """EDA-Schema Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNetlistGraph = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetNetlistGraph',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.NetlistEntity.FromString,
                _registered_method=True)
        self.GetCellMetrics = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetCellMetrics',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.CellMetricsEntity.FromString,
                _registered_method=True)
        self.GetAreaMetrics = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetAreaMetrics',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.AreaMetricsEntity.FromString,
                _registered_method=True)
        self.GetPowerMetrics = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetPowerMetrics',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.PowerMetricsEntity.FromString,
                _registered_method=True)
        self.GetTimingMetrics = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetTimingMetrics',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.TimingMetricsEntity.FromString,
                _registered_method=True)
        self.GetStandardCell = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetStandardCell',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.StandardCellEntity.FromString,
                _registered_method=True)
        self.GetGate = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetGate',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.GateEntity.FromString,
                _registered_method=True)
        self.GetPort = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetPort',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.PortEntity.FromString,
                _registered_method=True)
        self.GetNet = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetNet',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.NetEntity.FromString,
                _registered_method=True)
        self.GetTimingPathGraph = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetTimingPathGraph',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.TimingPathEntity.FromString,
                _registered_method=True)


class EdaSchemaServiceServicer(object):
    """EDA-Schema Service
    """

    def GetNetlistGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCellMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAreaMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPowerMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimingMetrics(self, request, context):
        """Changed: TimingMetrics instead of CriticalPathMetrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStandardCell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPort(self, request, context):
        """Changed: Port instead of IOPort
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNet(self, request, context):
        """Changed: Net instead of InterconnectGraph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimingPathGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdaSchemaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNetlistGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetlistGraph,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.NetlistEntity.SerializeToString,
            ),
            'GetCellMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCellMetrics,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.CellMetricsEntity.SerializeToString,
            ),
            'GetAreaMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAreaMetrics,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.AreaMetricsEntity.SerializeToString,
            ),
            'GetPowerMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPowerMetrics,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.PowerMetricsEntity.SerializeToString,
            ),
            'GetTimingMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimingMetrics,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.TimingMetricsEntity.SerializeToString,
            ),
            'GetStandardCell': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStandardCell,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.StandardCellEntity.SerializeToString,
            ),
            'GetGate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGate,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.GateEntity.SerializeToString,
            ),
            'GetPort': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPort,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.PortEntity.SerializeToString,
            ),
            'GetNet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNet,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.NetEntity.SerializeToString,
            ),
            'GetTimingPathGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimingPathGraph,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.TimingPathEntity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edaschema.EdaSchemaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edaschema.EdaSchemaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdaSchemaService(object):
    """EDA-Schema Service
    """

    @staticmethod
    def GetNetlistGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetNetlistGraph',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.NetlistEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCellMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetCellMetrics',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.CellMetricsEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAreaMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetAreaMetrics',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.AreaMetricsEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPowerMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetPowerMetrics',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.PowerMetricsEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimingMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetTimingMetrics',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.TimingMetricsEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStandardCell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetStandardCell',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.StandardCellEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetGate',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.GateEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetPort',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.PortEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetNet',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.NetEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimingPathGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetTimingPathGraph',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.TimingPathEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
