# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import eda_schema_pb2 as eda__schema__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in eda_schema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdaSchemaServiceStub(object):
    """EDA-Schema Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNetlistGraph = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetNetlistGraph',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.NetlistEntity.FromString,
                _registered_method=True)
        self.GetCellMetrics = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetCellMetrics',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.CellMetricsEntity.FromString,
                _registered_method=True)
        self.GetAreaMetrics = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetAreaMetrics',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.AreaMetricsEntity.FromString,
                _registered_method=True)
        self.GetPowerMetrics = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetPowerMetrics',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.PowerMetricsEntity.FromString,
                _registered_method=True)
        self.GetCriticalPathMetrics = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetCriticalPathMetrics',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.CriticalPathMetricsEntity.FromString,
                _registered_method=True)
        self.GetStandardCell = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetStandardCell',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.StandardCellEntity.FromString,
                _registered_method=True)
        self.GetGate = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetGate',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.GateEntity.FromString,
                _registered_method=True)
        self.GetIOPort = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetIOPort',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.IOPortEntity.FromString,
                _registered_method=True)
        self.GetInterconnectGraph = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetInterconnectGraph',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.InterconnectEntity.FromString,
                _registered_method=True)
        self.GetTimingPathGraph = channel.unary_unary(
                '/edaschema.EdaSchemaService/GetTimingPathGraph',
                request_serializer=eda__schema__pb2.Empty.SerializeToString,
                response_deserializer=eda__schema__pb2.TimingPathEntity.FromString,
                _registered_method=True)


class EdaSchemaServiceServicer(object):
    """EDA-Schema Service
    """

    def GetNetlistGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCellMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAreaMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPowerMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCriticalPathMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStandardCell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIOPort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterconnectGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimingPathGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdaSchemaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNetlistGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetlistGraph,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.NetlistEntity.SerializeToString,
            ),
            'GetCellMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCellMetrics,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.CellMetricsEntity.SerializeToString,
            ),
            'GetAreaMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAreaMetrics,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.AreaMetricsEntity.SerializeToString,
            ),
            'GetPowerMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPowerMetrics,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.PowerMetricsEntity.SerializeToString,
            ),
            'GetCriticalPathMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCriticalPathMetrics,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.CriticalPathMetricsEntity.SerializeToString,
            ),
            'GetStandardCell': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStandardCell,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.StandardCellEntity.SerializeToString,
            ),
            'GetGate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGate,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.GateEntity.SerializeToString,
            ),
            'GetIOPort': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIOPort,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.IOPortEntity.SerializeToString,
            ),
            'GetInterconnectGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterconnectGraph,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.InterconnectEntity.SerializeToString,
            ),
            'GetTimingPathGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimingPathGraph,
                    request_deserializer=eda__schema__pb2.Empty.FromString,
                    response_serializer=eda__schema__pb2.TimingPathEntity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edaschema.EdaSchemaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edaschema.EdaSchemaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdaSchemaService(object):
    """EDA-Schema Service
    """

    @staticmethod
    def GetNetlistGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetNetlistGraph',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.NetlistEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCellMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetCellMetrics',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.CellMetricsEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAreaMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetAreaMetrics',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.AreaMetricsEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPowerMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetPowerMetrics',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.PowerMetricsEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCriticalPathMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetCriticalPathMetrics',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.CriticalPathMetricsEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStandardCell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetStandardCell',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.StandardCellEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetGate',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.GateEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIOPort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetIOPort',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.IOPortEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInterconnectGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetInterconnectGraph',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.InterconnectEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimingPathGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EdaSchemaService/GetTimingPathGraph',
            eda__schema__pb2.Empty.SerializeToString,
            eda__schema__pb2.TimingPathEntity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EDAServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImportMethod = channel.unary_unary(
                '/edaschema.EDAService/ImportMethod',
                request_serializer=eda__schema__pb2.ImportRequest.SerializeToString,
                response_deserializer=eda__schema__pb2.ImportResponse.FromString,
                _registered_method=True)
        self.ExportMethod = channel.unary_unary(
                '/edaschema.EDAService/ExportMethod',
                request_serializer=eda__schema__pb2.ExportRequest.SerializeToString,
                response_deserializer=eda__schema__pb2.ExportResponse.FromString,
                _registered_method=True)


class EDAServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImportMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EDAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImportMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportMethod,
                    request_deserializer=eda__schema__pb2.ImportRequest.FromString,
                    response_serializer=eda__schema__pb2.ImportResponse.SerializeToString,
            ),
            'ExportMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportMethod,
                    request_deserializer=eda__schema__pb2.ExportRequest.FromString,
                    response_serializer=eda__schema__pb2.ExportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edaschema.EDAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edaschema.EDAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EDAService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImportMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EDAService/ImportMethod',
            eda__schema__pb2.ImportRequest.SerializeToString,
            eda__schema__pb2.ImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edaschema.EDAService/ExportMethod',
            eda__schema__pb2.ExportRequest.SerializeToString,
            eda__schema__pb2.ExportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
